name: BergLab
url: https://icebergnlp.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# Sections on the "people" page.
roles:
  - key: faculty
    name: Faculty
  - key: grad
    name: Graduate Students
  - key: ugrad
    name: Undergraduate Students
  - key: past
    name: Past Members

# Number of news stories on the front page.
front_page_news: 3

# Base pathname for links.
base: ''

# Navigation bar links.
navigation:
  - title: Home
    link: /
  - title: People
    link: /people
  - title: Publications
    link: /publications

# Icons
icons:
  homepage: fa-solid fa-earth-americas
  demo: fa-solid fa-earth-americas
  video: fa-brands fa-youtube
  paper: fa-solid fa-file-pdf
  slides: fa-solid fa-file-pdf
  poster: fa-solid fa-file-pdf
  arxiv: fa-solid fa-archive
  code: fa-brands fa-github
  documentation: fa-solid fa-book
  reviews: fa-solid fa-comments
